"""
Django settings for hnclone project.

Generated by 'django-admin startproject' using Django 2.2.5.

Modified by me 2019-09-30 15.50 CEST

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'TODO' # TODO

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


USE_X_FORWARDED_HOST = True
ALLOWED_HOSTS = [
    'localhost',
    'hacker-public-radio-dev.us-west-2.elasticbeanstalk.com',
    'podots.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'fontawesome-free',
    'mptt',
    'debug_toolbar',

    'accounts',
    'news',
    'emaildigest',
    # auto populate the allowed apps with the healthcheck IPs
    'ebhealthcheck.apps.EBHealthCheckConfig'
]

MIDDLEWARE = [
    # GZip middleware needs to placed before any other middleware
    'django.middleware.gzip.GZipMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    # Debug middleware needs to be the last entry
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'hnclone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hnclone.context_processors.settings_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'hnclone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# if RDS_HOSTNAME is set in the environment variables, it means we're running in elastic beanstalk and should connect to the postgres DB.
if 'RDS_HOSTNAME' in os.environ:
    # this AWS documentation was used to set up the RDS instance with elastic beanstalk: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-rds.html
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
# otherwise, we connect to the locally hosted sqlite database for development purposes.
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


AUTH_USER_MODEL = 'accounts.CustomUser'


INTERNAL_IPS = [
    '127.0.0.1',
]


PAGING_SIZE = 30


HTML_MINIFY = True



LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'



ACCEPT_UNINVITED_REGISTRATIONS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_HOST_USER = os.environ['EMAIL_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_PASS']

SITE_NAME = 'Podots'
#update these when we have a better domain name.
SITE_URL = 'http://hacker-public-radio-dev.us-west-2.elasticbeanstalk.com/'
SITE_DOMAIN = 'hacker-public-radio-dev.us-west-2.elasticbeanstalk.com'
