# Generated by Django 3.1.4 on 2021-01-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190923_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
